### ISSUE TITLE
Detect bad label names in `prog`

### ISSUE THREAD

**Issue by pdarragh** [cmsc430/a86#2]
Label names that happen to coincide with x86 instruction names that are not supported in a86 cause issues, but these errors are very opaque to students — especially when only certain versions of nasm report them. Add tests to `prog` (or `label`?) to check for these sorts of issues.

Example program:

```assembly
        default rel
        section .text
        global entry
entry:
        mov rax, 0
        mov rcx, rax
        mov rax, 0
        cmp rcx, 0
        je end
        jne rep
rep:
        pop r8
        add rax, r8
        sub rcx, 1
        cmp rcx, 0
        jne rep
end:
        ret
```

Error:

```sh
~ $ nasm test.s
test.s:10: error: expression syntax error
test.s:11: error: parser: instruction expected
test.s:16: error: expression syntax error
```

**Comment by dvanhorn** [comment]
I started working on this, but decided to stop and think about what the right approach is.

My initial idea was just to add a `reserved?` predicate and then check this in constructors that expect labels, raising an error if you tried to make a label that conflicts with instruction names like `mov`.  We already do this for register names, for example.

However, `nasm` has a mechanism for using reserved names in labels, which is the prefix `$` (and a86 could take advantage of it).  So for example, `$rax` is the *label* `rax`, not the register; the `$` is not part of the label name, but rather a way to indicate we're talking about a label.  So for example, these programs are alpha-equivalent:
```nasm
f:
        lea rax, [rel f]
        ret
```
and:
```nasm
$mov:
        lea rax, [rel mov]
        ret
```
Notice that the use of `mov` in `lea` instruction is unambiguously the label `mov`.  You could have used `$` there and it would mean the same thing:
```nasm
$mov:
        lea rax, [rel $mov]
        ret
```
But we can make an example where things are less clear.  This program is alpha equivalent to the above ones:
```nasm
$rax:
        lea rax, [rel $rax]
        ret
```
But this is a *different* valid program:
```nasm
$rax:
        lea rax, [rel rax]
        ret
```

OK, so what to do with a86?

My initial thought was to have `Label` prefix everything with `$` and remove the checks for things like register names.  But then what to do about label *references* in things like `Lea`?  You can't always prepend `$` because that may not be what was intended (as in the `rax` example.  You could leave it to the use to write `'$rax` but that leaks some nasmisms (and also will need to be dealt with in the `_` prefixing on Macs).

You could have users write `$` as part of the symbol, which is leaking nasmisms (and will have to work with `_` etc.), but then keep the `reserved?` check in the constructor.  Should it fail, the error message could suggest `$` as a fix.  This basically leaves it to the user to write things as they would in nasm.

Or, a more radical approach is to disentangle labels and register names from the same symbol representation, which would allow the `$` stuff to be handled automatically.  This would mean changing things like `(Lea rax s)` to `(Lea rax (Label s))`, i.e. anywhere you use a label, you use the label constructor; not just declarations, but uses as well.

So the `rax` example in a86 would be:
```racket
(Label 'rax)
(Lea 'rax 'rax)
(Ret)
```
And:
```racket
(Label 'rax)
(Lea 'rax (Label 'rax))
(Ret)
``` 
Then `Label` would always do `$` because you are definitely talking about a label.  This would require a rewrite of the notes, langs, and slides.

**Comment by dvanhorn** [comment]
You could also rename the label constructor `Label` to `$`:
```racket
($ 'rax)
(Lea 'rax ($ 'rax))
(Ret)
```
Which sort of amounts to enforcing a style guideline that label names *always* use `$`.

**Comment by dvanhorn** [comment]
Based on discussion with @pdarragh:

- internally represent labels and registers disjointly
- keep constructors as they are, taking symbols
- in positions that can be labels or registers (i.e. any memory expression), parse register names as registers, everything else as labels
- provide an explicit label constructor for when you want to override the parsing preference
- make the printer consistent with the parsing preference, i.e. labels that are register names print with the explicit label constructor, everything else prints as a symbol (so copy/paste is guaranteed to give you back what you started with).

A sketch:
```racket
(struct Lea (x y)
    #:transparent
    #:guard
    (λ (x y n)
      (values
       x
       (match y
         [(list '$ l) y]
         ['rax 'rax]
         [_ (cons '$ (list y))])))
  #:methods gen:custom-write
  [(define write-proc
     (lambda (instr port mode)
       (if (number? mode)
           (write-string "(" port)
           (write-string "#(struct:" port))
       (write-string "Lea" port)
       (let ([recur (case mode
                      [(#t) write]
                      [(#f) display]
                      [else (lambda (p port) (print p port mode))])])
         (for-each (lambda (e)
                     (write-string " " port)
                     (match e
                       [(list '$ 'rax) (recur e port)]
                       [(list '$ r) (recur r port)]
                       [_ (recur e port)]))
                   (rest (vector->list (struct->vector instr)))))
       (if (number? mode)
        (write-string ")" port)
        (write-string ")" port))))])
        
> (Lea 'rax 'foo)
(Lea 'rax 'foo)
> (Lea 'rax 'rax)
(Lea 'rax 'rax)
> (Lea 'rax '($ rax))
(Lea 'rax '($ rax))
> 
```

**Comment by dvanhorn** [comment]
When converting to nasm syntax, label names should all be prefixed with `$` so there's never any chance of conflicting with reserved keywords.

**Comment by dvanhorn** [comment]
These all work now:
```racket
;; Check that using label names that conflict with instruction names is fine
(check-equal?
 (asm-interp
  (prog (Global 'entry)
        (Label 'entry)
        (Mov 'rax 42)
        (Label 'mov)
        (Sub 'rax 1)
        (Cmp 'rax 0)
        (Jne 'mov)
        (Ret)))
 0)
        
;; Check that you can use labels names that coincide with registers with $
(check-equal?
 (asm-interp
  (prog (Global 'entry)
        (Label 'entry)
        (Mov 'rax 42)
        (Label 'rax)
        (Sub 'rax 1)
        (Cmp 'rax 0)
        (Jne ($ 'rax))
        (Ret)))
 0)

;; Check that $ can be used anywhere a label is expected
(check-equal?
 (asm-interp
  (prog (Global ($ 'entry))
        (Label ($ 'entry))
        (Mov 'rax 42)
        (Label ($ 'loop))
        (Sub 'rax 1)
        (Cmp 'rax 0)
        (Jne ($ 'loop))
        (Ret)))
 0)

;; Check that other reserved keywords are OK too
(check-equal?
 (asm-interp
  (prog (Global 'entry)
        (Label 'entry)
        (Mov 'rax 42)
        (Label 'pragma)
        (Sub 'rax 1)
        (Cmp 'rax 0)
        (Jne 'pragma)
        (Ret)))
 0)

(check-equal?
 (asm-interp
  (prog (Global 'entry)
        (Label 'entry)
        (Mov 'rax 42)
        (Label 'section)
        (Sub 'rax 1)
        (Cmp 'rax 0)
        (Jne 'section)
        (Ret)))
 0)
 ```

**Comment by dvanhorn** [comment]
See 12ad6a2.
